spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Be careful when use create(default validate).
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace